-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'cbde515f6a8e18ca' HASH 'a2192fb069e1591920f29c6ed7c27a2142c0c177ab7faa8a6efdd1b847ffa6fe' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."Account"(
    "accountId" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "accountType" CHARACTER VARYING(255),
    "amount" FLOAT(53),
    "creationDate" TIMESTAMP(6),
    "expirationDate" TIMESTAMP(6),
    "isBlocked" BOOLEAN,
    "isInDebt" BOOLEAN,
    "customerId" BIGINT NOT NULL
);   
ALTER TABLE "PUBLIC"."Account" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("accountId");               
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.Account; 
INSERT INTO "PUBLIC"."Account" VALUES
(1, 'Savings', 5000.0, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2026-01-01 00:00:00', FALSE, FALSE, 1),
(2, 'Checking', -100.0, TIMESTAMP '2022-05-10 00:00:00', TIMESTAMP '2025-05-10 00:00:00', FALSE, TRUE, 2); 
CREATE CACHED TABLE "PUBLIC"."Card"(
    "cardId" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "cvc" INTEGER NOT NULL,
    "expirationDate" TIMESTAMP(6),
    "number" BIGINT,
    "type" CHARACTER VARYING(255),
    "account_id" BIGINT NOT NULL
);           
ALTER TABLE "PUBLIC"."Card" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1F" PRIMARY KEY("cardId");    
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.Card;    
INSERT INTO "PUBLIC"."Card" VALUES
(1, 123, TIMESTAMP '2025-12-31 00:00:00', 1234567890123456, 'Credit', 1),
(2, 456, TIMESTAMP '2026-10-20 00:00:00', 9876543210123456, 'Debit', 2);       
CREATE CACHED TABLE "PUBLIC"."Customer"(
    "customerId" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 289) NOT NULL,
    "email" CHARACTER VARYING(255),
    "name" CHARACTER VARYING(255),
    "password" CHARACTER VARYING(255),
    "surname" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."Customer" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("customerId");             
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.Customer;
INSERT INTO "PUBLIC"."Customer" VALUES
(1, 'john.doe@example.com', 'John', 'password123', 'Doe'),
(2, 'jane.smith@example.com', 'Jane', 'securepass', 'Smith'),
(33, 'julia@sanz.com', 'Julia', 'hola', 'Sanz'),
(65, 'franro@email.es', 'Fran', '1234', 'Rodriguez'),
(66, 'jorgejimo@email.es', 'Jorge', '2432762', 'Jimenez'),
(97, 'customer@example.com', 'Jane', 'password123', 'Doe'),
(129, 'pepeG@email.es', 'pepito', '4466', 'grillo'),
(161, 'csan@email.com', 'carlos', '2334', 'sanchez');              
CREATE CACHED TABLE "PUBLIC"."Transfer"(
    "transferId" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "currencyType" ENUM('EUR', 'USD') NOT NULL,
    "transferAmount" FLOAT(53) NOT NULL,
    "transferDate" TIMESTAMP(6) NOT NULL,
    "transferStatus" ENUM('FAILED', 'PENDING', 'SUCCESSFUL') NOT NULL,
    "originAccountId" INTEGER NOT NULL,
    "receivingAccountId" INTEGER NOT NULL
);             
ALTER TABLE "PUBLIC"."Transfer" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("transferId");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.Transfer;
ALTER TABLE "PUBLIC"."Customer" ADD CONSTRAINT "PUBLIC"."UK3qgg01qojcmbdp47dkaom9x45" UNIQUE NULLS DISTINCT ("email");        
ALTER TABLE "PUBLIC"."Card" ADD CONSTRAINT "PUBLIC"."FKlysvqk4w1kwtyly1bh7iei4nl" FOREIGN KEY("account_id") REFERENCES "PUBLIC"."Account"("accountId") NOCHECK;               
ALTER TABLE "PUBLIC"."Transfer" ADD CONSTRAINT "PUBLIC"."FKc9okp77s80u7rbm6xqae8k5n7" FOREIGN KEY("receivingAccountId") REFERENCES "PUBLIC"."Account"("accountId") NOCHECK;   
ALTER TABLE "PUBLIC"."Transfer" ADD CONSTRAINT "PUBLIC"."FKfbfjrn8mktkla89423xurqr9x" FOREIGN KEY("originAccountId") REFERENCES "PUBLIC"."Account"("accountId") NOCHECK;      
ALTER TABLE "PUBLIC"."Account" ADD CONSTRAINT "PUBLIC"."FKdv4pd5yxpjc7j7mrrprwatiyc" FOREIGN KEY("customerId") REFERENCES "PUBLIC"."Customer"("customerId") NOCHECK;          
