-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'cbde515f6a8e18ca' HASH 'a2192fb069e1591920f29c6ed7c27a2142c0c177ab7faa8a6efdd1b847ffa6fe' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."Account"(
    "accountId" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 193) NOT NULL,
    "amount" FLOAT(53),
    "customerId" INTEGER NOT NULL,
    "isBlocked" BOOLEAN,
    "isInDebt" BOOLEAN,
    "creationDate" TIMESTAMP(6),
    "expirationDate" TIMESTAMP(6),
    "accountType" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."Account" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("accountId");               
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.Account; 
INSERT INTO "PUBLIC"."Account" VALUES
(1, 4890.0, 1, FALSE, FALSE, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2026-01-01 00:00:00', 'CHILDREN_ACCOUNT'),
(2, 10.0, 2, FALSE, FALSE, TIMESTAMP '2022-05-10 00:00:00', TIMESTAMP '2025-05-10 00:00:00', 'SAVINGS_ACCOUNT'),
(33, 800.0, 161, FALSE, FALSE, TIMESTAMP '2024-10-21 12:35:36.265007', TIMESTAMP '2025-10-21 12:35:36.265007', 'BUSINESS_ACCOUNT'),
(65, 800.0, 161, FALSE, FALSE, TIMESTAMP '2024-10-21 12:38:53.378858', TIMESTAMP '2025-10-21 12:38:53.378858', 'BUSINESS_ACCOUNT'),
(97, 800.0, 161, FALSE, FALSE, TIMESTAMP '2024-10-21 12:39:11.212618', TIMESTAMP '2025-10-21 12:39:11.212618', 'BUSINESS_ACCOUNT'),
(129, 800.0, 161, FALSE, FALSE, TIMESTAMP '2024-10-21 12:50:43.206184', TIMESTAMP '2025-10-21 12:50:43.206184', 'BUSINESS_ACCOUNT'),
(161, 800.0, 161, FALSE, FALSE, TIMESTAMP '2024-10-21 12:52:35.187724', TIMESTAMP '2025-10-21 12:52:35.187724', 'BUSINESS_ACCOUNT');       
CREATE CACHED TABLE "PUBLIC"."Card"(
    "account_id" INTEGER NOT NULL,
    "cardId" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "cvc" INTEGER NOT NULL,
    "expirationDate" TIMESTAMP(6),
    "number" BIGINT,
    "type" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."Card" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1F" PRIMARY KEY("cardId");    
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.Card;    
INSERT INTO "PUBLIC"."Card" VALUES
(1, 1, 123, TIMESTAMP '2025-12-31 00:00:00', 1234567890123456, 'Credit'),
(2, 2, 456, TIMESTAMP '2026-10-20 00:00:00', 9876543210123456, 'Debit');       
CREATE CACHED TABLE "PUBLIC"."Customer"(
    "customerId" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 641) NOT NULL,
    "email" CHARACTER VARYING(255) NOT NULL,
    "name" CHARACTER VARYING(255) NOT NULL,
    "password" CHARACTER VARYING(255) NOT NULL,
    "surname" CHARACTER VARYING(255) NOT NULL
);   
ALTER TABLE "PUBLIC"."Customer" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("customerId");            
-- 14 +/- SELECT COUNT(*) FROM PUBLIC.Customer;               
INSERT INTO "PUBLIC"."Customer" VALUES
(1, 'john.doe@example.com', 'John', 'password123', 'Doe'),
(2, 'jane.smith@example.com', 'Jane', 'securepass', 'Smith'),
(33, 'julia@sanz.com', 'Julia', 'hola', 'Sanz'),
(65, 'franro@email.es', 'Fran', '1234', 'Rodriguez'),
(66, 'jorgejimo@email.es', 'Jorge', '2432762', 'Jimenez'),
(97, 'customer@example.com', 'Jane', 'password123', 'Doe'),
(129, 'pepeG@email.es', 'pepito', '4466', 'grillo'),
(161, 'csan@email.com', 'carlos', '2334', 'sanchez'),
(193, 'new.user@example.com', 'New', 'newpassword', 'User'),
(353, 'testuser@example.com', 'John', 'password123', 'Doe'),
(385, 'probandoo@example.com', 'John', 'password123', 'Doe'),
(417, 'probando2@example.com', 'John', 'password123', 'Doe'),
(449, 'probando3@example.com', 'John', 'password123', 'Doe'),
(513, 'alice.johnson@example.com', 'Alice2', 'newpassword123', 'Johnson');         
CREATE CACHED TABLE "PUBLIC"."Transfer"(
    "originAccountId" INTEGER NOT NULL,
    "receivingAccountId" INTEGER NOT NULL,
    "transferAmount" FLOAT(53) NOT NULL,
    "transferId" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "transferDate" TIMESTAMP(6) NOT NULL,
    "currencyType" ENUM('EUR', 'USD') NOT NULL,
    "transferStatus" ENUM('FAILED', 'PENDING', 'SUCCESSFUL') NOT NULL
);             
ALTER TABLE "PUBLIC"."Transfer" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("transferId");             
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.Transfer;
INSERT INTO "PUBLIC"."Transfer" VALUES
(1, 2, 100.0, 1, TIMESTAMP '2024-10-15 12:48:58.235628', 'USD', 'PENDING'),
(1, 2, 100.0, 33, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'SUCCESSFUL'),
(1, 2, -1.0, 34, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'FAILED'),
(1, 2, 5000000.0, 35, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'FAILED'),
(2, 1, 30.0, 36, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'FAILED'),
(1, 2, 5.0E8, 65, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'FAILED'),
(1, 2, -2.0, 66, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'FAILED'),
(2, 1, 10.0, 67, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'FAILED'),
(1, 2, 10.0, 68, TIMESTAMP '2024-10-15 00:00:00', 'EUR', 'SUCCESSFUL');    
ALTER TABLE "PUBLIC"."Customer" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" UNIQUE NULLS DISTINCT ("email");       
ALTER TABLE "PUBLIC"."Customer" ADD CONSTRAINT "PUBLIC"."UK3qgg01qojcmbdp47dkaom9x45" UNIQUE NULLS DISTINCT ("email");        
ALTER TABLE "PUBLIC"."Card" ADD CONSTRAINT "PUBLIC"."FKlysvqk4w1kwtyly1bh7iei4nl" FOREIGN KEY("account_id") REFERENCES "PUBLIC"."Account"("accountId") NOCHECK;               
ALTER TABLE "PUBLIC"."Transfer" ADD CONSTRAINT "PUBLIC"."FKc9okp77s80u7rbm6xqae8k5n7" FOREIGN KEY("receivingAccountId") REFERENCES "PUBLIC"."Account"("accountId") NOCHECK;   
ALTER TABLE "PUBLIC"."Transfer" ADD CONSTRAINT "PUBLIC"."FKfbfjrn8mktkla89423xurqr9x" FOREIGN KEY("originAccountId") REFERENCES "PUBLIC"."Account"("accountId") NOCHECK;      
ALTER TABLE "PUBLIC"."Account" ADD CONSTRAINT "PUBLIC"."FKdv4pd5yxpjc7j7mrrprwatiyc" FOREIGN KEY("customerId") REFERENCES "PUBLIC"."Customer"("customerId") NOCHECK;          
